let quotes = [
    '"**I am Iron Man.**" - Tony Stark',
    '"**Dread it, run from it, destiny arrives all the same. And now it\'s here. Or should I say...I am.**" - Thanos',
    '"**This job...we try to save as many people as we can. Sometimes that doesn\'t mean everybody. But if we can\'t find a way to live with that, next time...maybe nobody gets saved.**" - Steve Rogers',
    '"**It\'s a hundred acres with a lap pool. It\'s got a screening room. There\'s worse ways to protect people. She\'s not a US citizen and they don\'t grant Visas to weapons of mass destruction.**" - Tony Stark',
    '"**I know we\'re not perfect, but the safest hands are still our own.**" - Steve Rogers',
    '"**I know what it\'s like to lose. To feel so desperately that you\'re right, yet to fail nonetheless. It\'s frightening. Turns the mind to jelly.**" - Thanos',
    '"**The work is done, and always will be. I am...inevitable.**" - Thanos',
    '"**I can\'t control their fear. Only my own.**" - Wanda Maximoff',
    '"**Language!**" - Steve Rogers',
    '"**You can\'t be a friendly neighborhood Spider-Man if there\'s no neighborhood.**" - Peter Parker',
    '"**You should have gone for the head.**" - Thanos',
    'Peter Quill: "**How the hell is this dude still alive?**"\nDrax: "**He is not a dude. You\'re a dude. This...this is a man. A handsome, muscular man.**"\nPeter Quill: "**I\'m muscular.**"\nRocket Raccoon: "**Who are you kidding, Quill? You\'re one sandwich away from fat.**"',
    '"**Dude, don\'t call us plucky. We don\'t know what it means. We\'re more optimistic. Yes, I like your plan, except, it sucks, so let *me* do the plan, and that way, it might be really good.**" - Peter Quill',
    '"**Dude, don\'t call us plucky. We don\'t know what it means. We\'re more optimistic. Yes, I like your plan, except, it sucks, so let *me* do the plan, and that way, it might be really good.**" - Peter Quill',
    'Tony Stark: “**Do we know if she had family?**"\nSteve Rogers: “**Yeah. Us.**"',
    '"**I\'m sorry, Earth is closed today. You\'d better pack it up and get outta here.**" - Tony Stark',
    '"**The universe is finite, its resources finite, if life is left unchecked, life will cease to exist.**" - Thanos',
    'Tony Stark: “**The Avengers broke up. We\'re toast.**"\nBruce Banner: “**Broke up? Like a band? L-like the Beatles?**"',
    '"**You\'re a seriously loyal piece of outerwear.**" - Tony Stark',
    '"**Today, we don\'t fight for any life...we fight for *all* of them.**" - T\'Challa',
    '"**Make a move, Reindeer Games.**" - Tony Stark',
    '"**I don\'t know if you\'ve been in a fight before, but there\'s usually not this much talking.**" - Sam Wilson',
    '"**Does anybody have any orange slices?**" - Scott Lang',
    '"**That man is playing *Galaga*! Thought we wouldn\'t notice, but we did.**" - Tony Stark',
    '"**This drink; I like it. Another!**" - Thor',
    '"**Doth mother know you weareth her drapes?**" - Tony Stark',
    '"**Nothing goes over my head. My reflexes are too fast, I would catch it.**" - Drax',
    '"**Let\'s do \'Get Help\'.**" - Thor',
    '"**We\'re just like Kevin Bacon.**" - Peter Quill',
    '"**Baskin-Robbins always finds out, bro!**" - Luis',
    '"**Dude, you\'re embarrassing me in front of the wizards.**" - Tony Stark',
    '"**It\'s like a pirate had a baby with an angel.**" - Drax',
    '"**You know you can\'t eat dumbbells, right?**" - Rocket Raccoon',
    '"**Hang on a second before you go swinging those jazz hands around, making a mess in your friend\'s house!**" - Talos',
    '"**I am Groot.**" - Groot',
    '"**He\'s a friend from work!**" - Thor',
    '"**The real question is *what are those!***" - Shuri',
    '"**I told you, I don\'t want to join your super secret boy band.**" - Tony Stark',
    'Peter Parker: "**No, Spider-Man isn\'t a party trick. Look, I\'m just gonna be myself.**"\nNed Leeds: "**Peter, no-one wants that!**"',
    'Stephen Strange: "**What\'s this, my mantra?**"\nKarl Mordo: "**It\'s the wifi password. We\'re not savages.**"',
    '"**Kick names, take ass.**" - Mantis',
    '"**The sun is going down.**" - Black Widow, Thor',
    '"**So, your body\'s changing. Believe me, I know how that feels.**" - Steve Rogers',
    '"**Hear me, and rejoice. You have had the privilege of being saved by the Mad Titan. You may think this is suffering. No. It is salvation. The universal scale tips towards balance because of your sacrifice. Smile, for even in death, you have become children of Thanos.**" - Ebony Maw',
    'Thor: "**Looks like you\'ve copied my beard. By the way, this is a friend of mine, Tree.**"\nGroot: "**I am Groot!**"\nSteve Rogers: "**I am Steve Rogers.**"',
    '"**The hardest choices require the strongest wills.**" - Thanos',
    'Red Skull (Stonekeeper): "**You should know...it extracts a terrible price.**"\nThanos: "**I am prepared.**"\nRed Skull (Stonekeeper): "**We all think that at first. We are all wrong.**"',
    'Stephen Strange: "**He could destroy life on a scale hitherto undreamt of.**"\nTony Stark: "**Did you seriously just say \'hitherto undreamt of?\'**"\nStephen Strange: "**Are you seriously leaning on the Cauldron of the Cosmos?**"\nTony Stark: [Leaning on the Cauldron] "**Is that what this is?**"\n[Cloak of Levitation slaps Tony]\nTony Stark: "**...I\'m going to allow that.**"',
    '"**Families can be tough. Before my father died, he told me that I had a half-sister that he imprisoned in Hel. Then she returned home and stabbed me in the eye. So I had to kill her. That\'s life though, isn\'t it? Goest round and round and...I feel your pain.**" - Thor',
    'Wanda Maximoff: "**That\'s too high a price.**"\nVision: "**Only you have the power to pay it.**"',
    '"**We don\'t trade lives, Vision.**" - Steve Rogers',
    'Peter Quill: I\'m gonna ask you this one time: Where is Gamora?\nTony Stark: I\'ll do you one better: *Who\'s* Gamora?\nDrax: I\'ll do *you* one better: *Why* is Gamora?',
    '"**I\'m not looking for forgiveness, and I\'m way past asking permission. Earth just lost her best defender, so we\'re here to fight. And if you stand in our way, we\'ll fight you too.**" - Steve Rogers',
]

module.exports = {
	name: 'quote',
	description: 'Sends the best MCU quotes!',
	execute(message, args) {
        var num = Math.floor( Math.random() * (quotes.length + 1) );
        message.channel.send(quotes[num])
	},
};